name: Prayer Song
favicon: null
layout_spectrum: 0.3117381944321096
typography_spectrum: 0.4246270104777068
title: Prayer Song Project
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#01121c'
    - '#322e9c'
    - '#6d81c8'
    - '#b7bfe4'
    - '#fafbfd'
  brandStrength: 0.19708380242809653
  lightness: 0.4072784981690347
  saturation: 0.14240732276812196
  rhythmicContrast: 0.09775565657764673
purpose: []
